export const instructionPrefix =
  'Antes de usar esta ferramenta, consulte get_instructions. ';
export const workInstructions = `# Work Track: conceitos e fluxo

- Projeto é compartilhado pela equipe; registros pertencem ao usuário autenticado. Pesquise com search_projects antes de registrar ou criar. Reutilize projetos/tópicos existentes e pergunte quando houver ambiguidade. Sem resultado, crie projeto com título e descrição do escopo.
- Tópicos contextualizam atividades dentro do projeto. Geral já existe para atividade sem contexto específico. Crie tópico somente quando necessário; vários tópicos não autorizam divisão automática de tempo. Preserve percentuais/durações somente quando informados; não invente repartição.
- register exige projeto e início, preserva originalText e interpretation. Resolva referências relativas ao momento da fala, não ao recebimento da transcrição. Informe timestamps com offset e fuso IANA; o orçamento diário interno usa America/Sao_Paulo. Não invente início/fim nem transforme estimativa de relatório em fato persistido. Registros retroativos só com informação humana explícita.
- Preserve interrupções e sobreposições: podem representar simultaneidade. Não encerre registros anteriores automaticamente. closePrevious é false por padrão; antes de true, pergunte e obtenha confirmação humana explícita e closePreviousReason. Fecha somente anterior aberto do mesmo usuário/projeto no início do novo registro. Múltiplos anteriores exigem closedPreviousRecordId explícito; não adivinhe. Sem anterior elegível, nenhum é fechado.
- update_record edita somente registro próprio com ID e motivo. endedAt null reabre explicitamente, nunca infira horário. Use requestId estável nos retries e expectedUpdatedAt quando disponível para detectar concorrência. Alterações de fatos têm auditoria; texto original e evidências são preservados.
- Confidencialidade/alias e modo seguro ocultam apresentação, não são autorização de acesso. Não exponha conteúdo confidencial em compartilhamento de tela ou saída desnecessária. Projetos são ativos por padrão; includeArchived permite histórico explícito.
- archive_project arquiva/desarquiva sem apagar histórico; origem mesclada não reabre. update_project exige ID, motivo e requestId estável. merge_projects começa com preview sem mutação; execução exige origem/destino, confirmação humana explícita, motivo e requestId. Cada chamada executa um lote limitado, retries retomam; não execute merge ou repita lotes automaticamente sem pedido. Cancelamento não desfaz lotes já migrados.
- Relatórios distinguem fatos e estimativas: orçamento global de 8h por pessoa/dia, fatos fechados nunca truncados. Estimativas não persistidas: até 4h/agora/meia-noite e próximo início elegível do mesmo projeto; candidatos fechados menores que 15min não cortam. Contexto incompleto falha com erro; não anuncie totais inventados.

Estas orientações são conceituais, não substituem consentimento humano, validação de dados nem autenticação. Consulte-as antes das demais ferramentas; não há bloqueio de sessão nem alteração de dados ao ler este guia.`;
