export const instructionPrefix =
  'Antes de usar esta ferramenta, consulte get_instructions. ';
export const workInstructions = `# Work Track: conceitos e fluxo

- Projeto exige tipo EXPLÍCITO escolhido pela pessoa: personal=pessoal, somente o proprietário autenticado tem acesso; work=corporativo, compartilhado com a organização. Se não informado, PERGUNTE antes de create_project; NUNCA infira/classifique nem use padrão silencioso. createdBy vem da identidade autenticada, não do cliente. Projetos antigos sem tipo preservam o contrato corporativo; não converta existentes automaticamente. Registros pertencem ao usuário autenticado. Pesquise com search_projects antes de registrar ou criar; a busca só retorna projetos autorizados. Reutilize projetos/tópicos existentes e pergunte quando houver ambiguidade. Sem resultado, crie com título, descrição e tipo humano explícito.
- Tópicos contextualizam atividades dentro do projeto. Geral já existe para atividade sem contexto específico. Crie tópico somente quando necessário; vários tópicos não autorizam divisão automática de tempo. Preserve percentuais/durações somente quando informados; não invente repartição.
- register exige projeto e início, preserva originalText e interpretation. Resolva referências relativas ao momento da fala, não ao recebimento da transcrição. Informe timestamps com offset e fuso IANA; o orçamento diário interno usa America/Sao_Paulo. Não invente início/fim nem transforme estimativa de relatório em fato persistido. Registros retroativos só com informação humana explícita.
- Preserve interrupções e sobreposições: podem representar simultaneidade. Não encerre registros anteriores automaticamente. closePrevious é false por padrão; antes de true, pergunte e obtenha confirmação humana explícita e closePreviousReason. Fecha somente anterior aberto do mesmo usuário/projeto no início do novo registro. Múltiplos anteriores exigem closedPreviousRecordId explícito; não adivinhe. Sem anterior elegível, nenhum é fechado.
- split_record divide trecho explícito de fato próprio encerrado. Prévia é somente leitura: apresente todos os segmentos, horas totais, assuntos e texto preservado, especialmente transferência pessoal para projeto corporativo (texto ficará compartilhado). Em pessoal para corporativo a confirmação explícita de publicação exige acknowledgeSharedDestination true; nunca presuma esse aceite. Só após confirmação humana execute confirmed true com previewToken, requestId estável e motivo idênticos. Original mantém ID do primeiro segmento cronológico (pode mudar para projeto destino); demais IDs determinísticos. Não invente fim, percentuais ou repartição de interrupções/minutos absolutos: ambiguidades retornam erro sem alteração; não peça apagar evidências. Não implementa faturamento, abono ou desfazer.
- update_record edita somente registro próprio com ID e motivo. endedAt null reabre explicitamente, nunca infira horário. Use requestId estável nos retries e expectedUpdatedAt quando disponível para detectar concorrência. Alterações de fatos têm auditoria; texto original e evidências são preservados.
- Confidencialidade/alias e modo seguro ocultam apresentação, não são autorização de acesso. Não exponha conteúdo confidencial em compartilhamento de tela ou saída desnecessária. Projetos são ativos por padrão; includeArchived permite histórico explícito.
- update_project não permite mudar tipo/escopo; a página do projeto oferece changeProjectScope (callable, não ferramenta MCP): somente criador identificado, tipo atual explícito, prévia sem escrita, confirmação/token/motivo/requestId e aceite explícito de publicação pessoal para Global. Global significa organização, não Internet; confidencial não limita acesso. Limite 2000 registros físicos, incluindo removidos; bloqueia participantes alheios, escopo legado desconhecido e histórico de mesclagem. Preserva registros e auditoria antes/depois do projeto; não revoga cópias já lidas. merge_projects não cruza pessoal/corporativo nem proprietários pessoais. Tópicos, auditorias, registros e retries respeitam o acesso atual ao projeto; pessoal alheio é indistinguível de inexistente.
- archive_project arquiva/desarquiva sem apagar histórico; origem mesclada não reabre. update_project exige ID, motivo e requestId estável. merge_projects começa com preview sem mutação; execução exige origem/destino, confirmação humana explícita, motivo e requestId. Cada chamada executa um lote limitado, retries retomam; não execute merge ou repita lotes automaticamente sem pedido. Cancelamento não desfaz lotes já migrados.
- merge_topics unifica tópicos explicitamente escolhidos do MESMO projeto: preview sem escrita; confirmação humana, motivo e requestId estável para executar. Origem Geral não pode ser unificada. Aliases arquivados preservam IDs e snapshots históricos; novos registros resolvem o destino canônico. Não invente contagem de impacto não escaneada; list_topic_merges pagina auditoria antes/depois. Não existe desfazer nesta versão.
- Relatórios distinguem fatos e estimativas: orçamento global de 8h por pessoa/dia, fatos fechados nunca truncados. Estimativas não persistidas: até 4h/agora/meia-noite e próximo início elegível do mesmo projeto; candidatos fechados menores que 15min não cortam. Contexto incompleto falha com erro; não anuncie totais inventados.

- Pausa passada em minutos explícitos: register_pause exige resumedAt ISO do momento da fala/retomada, durationMinutes, requestId estável, motivo e originalUtterance. Nunca use horário do recebimento para retroagir. Somente registro próprio aberto iniciado há menos de24h; sem elegível, erro e nenhuma alteração; múltiplos exigem perguntar recordId explícito. Fecha no início da pausa e cria retomada atômica no mesmo projeto/contexto. Não invente duração nem duplique minutos absolutos de tópicos; conciliação antiga/ambígua exige fluxo separado. Frase futura “vou pausar”: NÃO register_pause; use update_record para encerrar agora, sem criar retomada.

- remove_record: remoção lógica de registro próprio, inclusive aberto/órfão. Nunca apague físico nem invente fim. Execute prévia com recordId, requestId estável e motivo; apresente o registro e aviso de impacto nas horas e estimativas, peça confirmação humana explícita; somente depois confirmed:true com o mesmo previewToken. Registro removido não aparece em leituras funcionais, horas, próximo início, orçamento, nem candidatos a pausa/edição/divisão. Não tenta recriar com mesmo requestId; auditoria e texto são preservados. Não há desfazer nem remoção automática de outros segmentos ligados.

Estas orientações são conceituais, não substituem consentimento humano, validação de dados nem autenticação. Consulte-as antes das demais ferramentas; não há bloqueio de sessão nem alteração de dados ao ler este guia.`;
