import {
  Bell,
  Info,
  Folder,
  House,
  Eye,
  EyeOff,
  Sun,
  Moon,
  RefreshCw,
  Menu,
  ChevronLeft,
  ChevronRight,
  SlidersHorizontal,
  BookOpen,
  X,
  Pencil,
  ExternalLink,
  History,
  Archive,
  CalendarDays,
  ListChecks,
  ChartNoAxesCombined,
} from 'lucide-react';
const icons = {
  detail: Info,
  bell: Bell,
  rules: BookOpen,
  projects: Folder,
  home: House,
  eye: Eye,
  eyeoff: EyeOff,
  sun: Sun,
  moon: Moon,
  refresh: RefreshCw,
  menu: Menu,
  previous: ChevronLeft,
  next: ChevronRight,
  filter: SlidersHorizontal,
  close: X,
  edit: Pencil,
  page: ExternalLink,
  history: History,
  archive: Archive,
  calendar: CalendarDays,
  records: ListChecks,
  chart: ChartNoAxesCombined,
};
export function UiIcon({ kind }: { kind: keyof typeof icons }) {
  const Icon = icons[kind];
  return <Icon size={20} strokeWidth={1.8} aria-hidden="true" />;
}
